tracert 114.113.148.240 >c:\tracert\优阅外文原版电子书.txt
tracert 182.18.14.17 >c:\tracert\HKMO港澳优秀学术全文资源库.txt
tracert agupubs.onlinelibrary.wiley.com >c:\tracert\AGU电子期刊.txt
tracert arc.aiaa.org >c:\tracert\AIAA.txt
tracert ascelibrary.org >c:\tracert\ASCE.txt
tracert asmedigitalcollection.asme.org >c:\tracert\ASME.txt
tracert bg.sunwayinfo.com.cn >c:\tracert\尚唯科技报告.txt
tracert dl.acm.org >c:\tracert\ACM.txt
tracert ebook.worldlib.com.cn >c:\tracert\WorldlibE-BOOK外文原版图书.txt
tracert epubs.siam.org >c:\tracert\SIAM.txt
tracert esi.incites.thomsonreuters.com >c:\tracert\ESI.txt
tracert incites.thomsonreuters.com >c:\tracert\InCites.txt
tracert journal.hep.com.cn >c:\tracert\Frontiers期刊全文库.txt
tracert journals.ametsoc.org >c:\tracert\AMS.txt
tracert journals.aps.org >c:\tracert\APS.txt
tracert journals.sagepub.com >c:\tracert\Sage.txt
tracert mgts.shutu.tv >c:\tracert\美国探索教育视频资源.txt
tracert onlinelibrary.wiley.com >c:\tracert\Wiley.txt
tracert portal.acm.org >c:\tracert\ACM会议论文.txt
tracert pqdt.bjzhongke.com.cn >c:\tracert\PQDT学位论文全文.txt
tracert pqdt.lib.sjtu.edu.cn >c:\tracert\PQDT入口2.txt
tracert pubs.acs.org >c:\tracert\ACS.txt
tracert search.ebscohost.com >c:\tracert\EBSCO.txt
tracert sjmx.shutu.tv >c:\tracert\世界名校精品课程.txt
tracert spiedigitallibrary.org >c:\tracert\SPIE.txt
tracert v2017.specialsci.cn >c:\tracert\SpecialSci.txt
tracert www.aip.org >c:\tracert\AIP.txt
tracert www.annualreviews.org >c:\tracert\AnnualReviews.txt
tracert www.bjadks.com >c:\tracert\IET.tv视频数据库.txt
tracert www.cambridge.org >c:\tracert\Cambridgejournals.txt
tracert www.cashl.edu.cn >c:\tracert\CASHL.txt
tracert www.emeraldinsight.com >c:\tracert\Emerald.txt
tracert www.engineeringvillage.com >c:\tracert\EiCompendex.txt
tracert www.HICDS.cn >c:\tracert\国道会议发现系统-HICDS.txt
tracert www.ieeexplore.ieee.org >c:\tracert\IEEE-IET期刊-会议.txt
tracert www.iop.org >c:\tracert\IOP.txt
tracert www.istic.ac.cn >c:\tracert\ISTIC.txt
tracert www.jstor.org >c:\tracert\JSTOR回溯期刊.txt
tracert www.MeTeL.cn >c:\tracert\MeTeL.txt
tracert www.nature.com >c:\tracert\NatureOnline.txt
tracert www.OADDS.cn >c:\tracert\国道学位论文发现系统-DDS.txt
tracert www.opticsinfobase.org >c:\tracert\OSA.txt
tracert www.oxfordjournals.org >c:\tracert\Oxfordjournals.txt
tracert www.pnas.org >c:\tracert\PNAS.txt
tracert www.sciencedirect.com >c:\tracert\Elsevier.txt
tracert www.sciencemag.org >c:\tracert\ScienceOnline.txt
tracert www.socolar.com >c:\tracert\Socolar检索系统.txt
tracert www.spischolar.com >c:\tracert\SpiScholar学术资源在线.txt
tracert www.springerlink.com >c:\tracert\Springer期刊-会议.txt
tracert www.tandfonline.com >c:\tracert\Taylor-Francis.txt
tracert www.webofknowledge.com >c:\tracert\SCI-CPCI-S.txt
